const mongoose = require('mongoose');
let Schema = mongoose.Schema;

let AffixSchema = Schema({
  name: {type: String, required: true},
  descShort: {type: String, required: true},
  descLong: {type: String, required: true},
  source: {
    type: String, 
    enum: ['core:phb', 'core:animism', 'core:ws'],
    required: true,
  },
  cost: {
    type: Number,
    min: 0,
    default: 1,
  },
  maxReplicates: {
    type: Number,
    min: 0,
    default: 1,
  },
  doubleEdged: {type: Boolean, default: false},
  slot: {
    type: String,
    enum: ['Arms', 'Armor', 'Trinket', 'Consumable'],
    required: true,
  },
  affixType: {
    type: String,
    enum: ['Magical', 'Elemental', 'Prismatic', 'Mundane'],
    required: true,
  },
  prerequisites: String,
  categories: {
    type: [String],
    enum: [
      'Absorption',
      'Actions',
      'Active',
      'Advantage',
      'Affliction',
      'Affliction. critical',
      'Agile',
      'Aquatic',
      'Area',
      'Attributes',
      'Basic attack',
      'Basic attacks',
      'Blocking',
      'Brace',
      'Brawling',
      'Concentration',
      'Condition',
      'Counter',
      'Critical',
      'Damage',
      'Defend',
      'Defense',
      'Defensive',
      'Difficult terrain',
      'Displacement',
      'Downtime',
      'Elements',
      'Essence',
      'Exhaustion',
      'Flying',
      'Grappling',
      'Guarding',
      'Healing',
      'Item',
      'Items',
      'Life',
      'Light',
      'Low life',
      'Luck',
      'Meta',
      'Movement',
      'Offensive',
      'Offensive defense',
      'Powers',
      'Protecting',
      'Range',
      'Ranged',
      'Reactions',
      'Reactive',
      'Senses',
      'Shaping',
      'Size',
      'Social',
      'Special attack',
      'Special attacks',
      'Splitting',
      'Stealth',
      'Support',
      'Threaten',
      'Throwing',
      'Thrown',
      'Utility',
      'Zone',
    ]
  },
  elements: {
    type: [String],
    enum: [
      'Physical', 
      'Arcane', 
      'Eldritch', 
      'Air', 
      'Earth', 
      'Fire', 
      'Water', 
      'Primal', 
      'Decay', 
      'Radaint', 
      'Umbral', 
      'Corrosion', 
      'Electric',
      'Specified',
    ],
  }
});

module.exports = mongoose.model('Affix', AffixSchema);
